baseURL = "https://edu2610.github.io/"   # si fuera Project Page: "https://edu2610.github.io/tu-repo/"
title = "Eduardo Vergara — Portafolio"
languageCode = "es"
theme = "PaperMod"
canonifyURLs = true

[params]
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowShareButtons = true
  showFooter = true          # asegura que se renderice el footer

  # Home tipo texto (si luego activas profileMode, puedes comentar este bloque)
  [params.homeInfoParams]
    Title = "Eduardo Vergara"
    Content = "Programación, IA aplicada a educación y recursos docentes."

# ===== Menú superior =====
[menu]
  [[menu.main]]
    name = "Inicio"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Proyectos"
    url = "/proyectos/"
    weight = 2
  [[menu.main]]
    name = "Educación"
    url = "/educacion/"
    weight = 3
  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 4
  [[menu.main]]
    name = "Sobre mí"
    url = "/about/"
    weight = 5
  [[menu.main]]
    name = "Contacto"
    url = "/contacto/"
    weight = 6

# ===== Redes sociales en footer (usar siempre arreglo de tablas) =====
[[params.socialIcons]]
  name = "github"
  url  = "https://github.com/Edu2610"

[[params.socialIcons]]
  name = "linkedin"
  url  = "https://www.linkedin.com/in/eduardo-ignacio-vergara-morales-3628482a3"

[[params.socialIcons]]
  name = "youtube"
  url  = "https://www.youtube.com/@MatesConCafé"

# (opcional) email en el footer
[[params.socialIcons]]
  name = "email"
  url  = "mailto:tucorreo@ejemplo.com"

# ===== Opcional: si quieres portada con avatar/botones e iconos grandes =====
# [params.profileMode]
#   enabled = true
#   title = "Eduardo Vergara"
#   subtitle = "Programación, IA aplicada a educación y recursos docentes."
#   imageUrl = "/images/avatar.jpg"  # sube un avatar a static/images/
#   imageWidth = 160
#   imageHeight = 160
#   imageTitle = "Eduardo"
#   [[params.profileMode.buttons]]
#     name = "Proyectos"
#     url  = "/proyectos/"
#   [[params.profileMode.buttons]]
#     name = "Contacto"
#     url  = "/contacto/"

# ===== Evitar confusiones con assets fingerprint (puedes dejarlo así) =====
[params.assets]
  disableFingerprinting = true
