baseURL = "https://edu2610.github.io/"        # o tu baseURL con subcarpeta, si aplica
title = "Eduardo Vergara — Portafolio"
languageCode = "es"
theme = "PaperMod"
canonifyURLs = true

[params]
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowShareButtons = true

  [params.homeInfoParams]
    Title = "Eduardo Vergara"
    Content = "Programación, IA aplicada a educación y recursos docentes."

[menu]
  [[menu.main]]
    name = "Inicio"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Proyectos"
    url = "/proyectos/"
    weight = 2
  [[menu.main]]
    name = "Educación"
    url = "/educacion/"
    weight = 3
  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 4
  [[menu.main]]
    name = "Sobre mí"
    url = "/about/"
    weight = 5
  [[menu.main]]
    name = "Contacto"
    url = "/contacto/"
    weight = 6

# Íconos sociales: usar siempre arreglo de tablas
[[params.socialIcons]]
  name = "github"
  url  = "https://github.com/Edu2610"

[[params.socialIcons]]
  name = "linkedin"
  url  = "https://www.linkedin.com/in/eduardo-ignacio-vergara-morales-3628482a3"

[[params.socialIcons]]
  name = "youtube"
  url  = "https://www.youtube.com/@MatesConCafé"

[params.assets]
  disableFingerprinting = true
 