baseURL = "https://edu2610.github.io/"
title = "Eduardo Vergara — Portafolio"
languageCode = "es"
theme = "PaperMod"
canonifyURLs = true

[params]
  defaultTheme = "auto"

[params.assets]
  disableFingerprinting = true
